### PR TITLE
Add how to review the manual

### PR DESCRIPTION
**Pull request by bethwalton**

### CODE REVIEW

**Review by Ian-Nicholls — CHANGES_REQUESTED** [review]
change Github to GitHub :)

**Review by Ian-Nicholls — APPROVED** [review]
Great :)

**Review by Ian-Nicholls — APPROVED** [review]
good with 2nd change

**Review by Ian-Nicholls — APPROVED** [review]
Approved!!!

**Review by Ian-Nicholls — APPROVED** [review]
Approved x 4 :)

**Review by seb-szy — APPROVED** [review]
Let me try to approve it.

**Pull request merged**
