### PR TITLE
Content changes 

### PR DESCRIPTION
**Pull request by bethwalton**
## What

- Break sections down into subpages (e.g. instead of long page like https://govwifi-dev-docs.cloudapps.digital/accessing-the-infrastructure.html#users-database) - this would hopefully make the navigation sidebar more usable (see below for a before and after view) and improve readability of individual pages by breaking large sections down into multiple pages
- Reorganise and reshuffle pages for better/more logical organisation
- Add some new pages that the team said would be useful
- Add a new page on certification rotation
- Improve some existing pages so they're up-to-date and easier to read
- Fix broken links

## Why

The team manual was confusing and overwhelming. We decided to work on improving it, using feedback from the team, during the Firebreak.

## How to review

- Anyone on the team can review the content changes on GitHub
- Devs should probably take it for a spin on their local environment as well

---

### Further information

For more context on the actual changes and the rationale behind the reorganisation, [refer to this doc](https://docs.google.com/document/d/1K-yUWiQAjSNIuGdWwcfSD96EjSK-kNgFrWJ0C5ONy84/edit?ts=5ff735f3#heading=h.j8574n5zbpf1).

### Navigation structure simplification

**BEFORE**
govwifi-dev-docs cloudapps digital_ (2)
*congratulations if you've reached the bottom ;)*

**AFTER**

localhost_4567_ (1)

### CODE REVIEW

**Review by robinmitra — APPROVED** [review]
LGTM 🚀

**Review by sarahseewhy — APPROVED** [review]
LGTM 🎉

**Review by camdesgov — COMMENTED** [review]
Looks great Beth! Thanks for doing this

**Comment by ihateusernames** [comment]
Gosh! It looks tons better than the old one Beth.

**Pull request merged**
