### PR TITLE
Add support for running in Docker locally

### PR DESCRIPTION
**Pull request by robinmitra**

### CODE REVIEW

**Comment by robinmitra** [comment]
Don't review yet, I'll update the README as well.

**Comment by robinmitra** [comment]
Ready for review now.

**Comment by robinmitra** [comment]
> Great work, Robin!
> 
> It'd be worth mentioning `make`/`docker` in the README, but that can be done separately. The same goes for govwifi-tech-docs, in fact, even though docker has already been set up in there for quite a while. I'll have a go at writing some README updates for the two repos.

Cheers Alan, there's a bit about this in the README: https://github.com/alphagov/govwifi-dev-docs/pull/47/files#diff-04c6e90faac2675aa89e2176d2eec7d8R45

Perhaps you meant adding more context, so feel free to improve that aspect 👍

**Comment by alan-gds** [comment]
D'oh, I completely missed the README update - I forgot there was a second commit!

**Pull request merged**
